    
worker_processes auto;

events {
    worker_connections 1024;
}

http {

    include mime.types;

    gzip on;
    gzip_comp_level 4;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:30m inactive=60s use_temp_path=off;

    limit_req_zone $binary_remote_addr zone=rate_limit:10m rate=10r/s;

    server {

        # listen 443 ssl;
        listen  80;

        server_name localhost;
        # ssl_certificate /etc/nginx/ssl/public.pem;
        # ssl_certificate_key /etc/nginx/ssl/private.key;
        root /var/mates/dist;

        index index.html;

        location ~* /api/(rooms|messages)/ {
            proxy_pass http://chat-service:8080;

#            proxy_cache my_cache;
#            proxy_cache_valid 200 5s;
#            proxy_cache_use_stale error timeout updating;
#            add_header X-Cache $upstream_cache_status;

            limit_req zone=rate_limit burst=50 nodelay;
        }

        location /api/auth/ {
            proxy_pass http://users-service:8000;
            limit_req zone=rate_limit burst=50 nodelay;
        }

        location /ws/ {
            proxy_pass http://chat-service:8080;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            limit_req zone=rate_limit burst=50 nodelay;
        }

	location = /stub_status {
	    stub_status;
	}

	location ^~ /monitor/ {
	    proxy_pass http://grafana:3000;

	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Proto $scheme;
	    proxy_set_header X-Forwarded-Prefix /monitor;
	}

	location /monitor/api/live/ {
	    proxy_http_version 1.1;
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection "upgrade";
	    proxy_set_header Host $host;
	    proxy_pass http://grafana:3000/api/live/;
	}

        location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg)$ {
            add_header Cache-Control "public, max-age=2592000, immutable";
            add_header Pragma public;
            add_header Vary Accept-Encoding;
            expires 1M;
            access_log off;
        }

        location  / {
            try_files $uri $uri/ /index.html;
        }


    }
}
