version: "3"
services:
  django:
    container_name: django-container
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: kirigaya_kazut0
      POSTGRES_USER: postgres
      POSTGRES_DB: mates
