services:


## PROM ##

  prometheus:
    image: prom/prometheus:main-distroless

    ports:
    - 9090:9090

    volumes:
    - ./prometheus/prometheus.2.yml:/etc/prometheus/prometheus.yml
    # - prometheus-data:/prometheus

    restart: unless-stopped

    # networks:
    #   - monitoring-net
    # depends_on:
    #   cadvisor:
    #     condition: service_healthy


## GRAFANA ##

  grafana:
    image: grafana/grafana:nightly-slim

    ports:
    - 3000:3000

    restart: unless-stopped

    # volumes:
    # - grafana-storage:/var/lib/grafana
    # - ../../monitoring/grafana/provisioning:/etc/grafana/provisioning

    # networks:
    #   - monitoring-net

    #logging:
    #  driver: none

    environment:
      GF_SERVER_ROOT_URL: http://localhost/monitor/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

    # depends_on:
    #   prometheus:
    #     condition: service_healthy



## DATABASUS ##

  databasus:
    container_name: databasus
    image: databasus/databasus:latest
    ports:
      - "4005:4005"
    volumes:
      - ./databasus-data:/databasus-data
    restart: unless-stopped