api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: DEBUG

entryPoints:
  nonSecure: 
    address: ":80"
  secure:
    address: ":443"