
include:
  - ./services/front.yml
  - ./services/users.svc.yml
  - ./services/chat.svc.yml
  - ./services/celery.yml
  # - ./services/monitor.yml
  # - ./services/exporters.yml
  - ./services/traefik.yml

volumes:
  mates-db-users:
  mates-db-chat:
  grafana-storage:
  prometheus-data:

networks:
  traefik-net:
    driver: bridge

  front-net:
    driver: bridge
    internal: true

  users-back-net:
    driver: bridge
    internal: true
  
  users-db-net:
    driver: bridge
    internal: true
  
  chat-back-net:
    driver: bridge
    internal: true

  chat-db-net:
    driver: bridge
    internal: true

  celery-net:
    driver: bridge
    internal: true

  monitoring-net:
    internal: true
