
include:
  - ./services/front.yml
  - ./services/users.svc.yml
  - ./services/chat.svc.yml
  - ./services/celery.yml
  - ./services/monitor.yml
  - ./services/exporters.yml

volumes:
  mates-db-users:
  mates-db-chat:
  grafana-storage:
  prometheus-data:

networks:
  front-net:
    driver: bridge

  users-back-net:
    driver: bridge
    #internal: true
  
  users-db-net:
    driver: bridge
    internal: true
  
  chat-back-net:
    driver: bridge
    internal: true

  chat-db-net:
    driver: bridge
    internal: true

  celery-net:
    driver: bridge
    internal: true

  monitoring-net:
  #  internal: true
