name: chat ci workflow

on:
  push:
    branches:
      - main
      - development
    paths:
      - "backend/chat/**"

jobs:
  test:
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB:        ${{secrets.POSTGRES_DB}}
          POSTGRES_USER:      ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD:  ${{secrets.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    
    runs-on: ubuntu-latest
    environment: prod
    env:
      SECRET_KEY:         ${{secrets.SECRET_KEY}}
      POSTGRES_DB:        ${{secrets.POSTGRES_DB}}
      POSTGRES_USER:      ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD:  ${{secrets.POSTGRES_PASSWORD}}
      DB_HOST:            ${{secrets.DB_HOST}}
      DB_PORT:            ${{secrets.DB_PORT}}

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: install reqs
        run: pip install -r backend/chat/requirements.txt

      - name: run tests
        run: cd backend/chat && pytest